name: Terra Sports Consignment
favicon: null
layout_spectrum: 0.89173
typography_spectrum: 0.07677
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f4ae5e'
    - '#b93500'
    - '#f3f8e8'
    - '#522936'
  brandStrength: 0.5625
  lightness: 0.17064239457249641
  saturation: 0.6792060637380928
  rhythmicContrast: 0.008852598024532199
purpose: []
