name: Terra Sports Consignment
favicon: null
layout_spectrum: 0.60334
typography_spectrum: 0.97146
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77003902-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#53c0c3'
    - '#f1f0ee'
    - '#2862a1'
    - '#578fc0'
    - '#212934'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.6792060637380928
  rhythmicContrast: 0.5
purpose: []
